# Common properties
server:
  port: 8080
---
# Default profile (dev) configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prd_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    include: dev